# Default values for plateforme-ebs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

php:
  image:
    repository: "ghcr.io/apes-hdf/plateforme-ebs-php" # CHANGE ME
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  appEnv: prod
  appDebug: "0"
  appSecret: ""
  corsAllowOrigin: "^https?://.*?\\.chart-example\\.local$"
  trustedHosts: "^127\\.0\\.0\\.1|localhost|.*\\.chart-example\\.local$"
  trustedProxies:
    - "127.0.0.1"
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
  host: "ebs.chart-example.local"
  jwt:
    secretKey: ""
    publicKey: ""
    passphrase: ""
  storage:
    bucket: ""
    endpoint: ""
    region: ""
    usePathStyleEndpoint: true
    publicKey: ""
    secret: ""
  fixtureCron:
    enabled: false
  fixtureJob:
    enabled: false

dailyCronjobs:
  enabled: true

maildev:
  enabled: false

mailer:
  # is set automaticaly if maildev is enabled
  dsn: change_me

sms:
  dsn: "null://null"

consumer:
  # We don't use async for now so consumer isn't needed
  enabled: false

caddy:
  image:
    repository: "ghcr.io/apes-hdf/plateforme-ebs-caddy" # CHANGE ME
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

# You may prefer using the managed version in production: https://mercure.rocks
mercure:
  publicUrl: https://ghcr.io/.well-known/mercure
  # Change me!
  jwtSecret: "!ChangeThisMercureHubJWTSecretKey!"
  extraDirectives: cors_origins http://ghcr.io https://ghcr.io

# Full configuration: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
postgresql:
  enabled: true
  # If bringing your own PostgreSQL, the full uri to use
  # url: postgresql://plateforme-ebs:!ChangeMe!@database:5432/api?serverVersion=13&charset=utf8
  global:
    postgresql:
      auth:
        username: "example"
        password: "!ChangeMe!"
        database: "api"
        postgresPassword: "!ChangeMe!"
  # Persistent Volume Storage configuration.
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  pullPolicy: IfNotPresent
  image:
    repository: bitnami/postgresql
    tag: 14
  primary:
    persistence:
      enabled: true
      storageClass: standard
      size: 1Gi
    resources:
      requests:
        memory: 50Mi
        cpu: 1m

payum:
  # @see https://my.mollie.com/dashboard/org_XXXXXXXX/developers/api-keys
  # even it's a fake key it must start with 'test_' or 'live_' and must be at least 30 characters long
  gateway: "mollie"
  apikey: "test_FRabcdefghijklmnopqrstuvwxyzab"

external-dns:
  enabled: false
  domainFilters:
    - demo.local
  provider: cloudflare
  cloudflare:
    apiToken: ""
  zoneIdFilters: []
  rbac:
    create: true

# https://artifacthub.io/packages/helm/bitnami/redis
redis:
  enabled: true
  auth:
    enabled: false
  master:
    startupProbe:
      enabled: true
      initialDelaySeconds: 1
      periodSeconds: 1
    livenessProbe:
      initialDelaySeconds: 0
    readinessProbe:
      initialDelaySeconds: 0
  replica:
    replicaCount: 0

# https://github.com/meilisearch/meilisearch-kubernetes/blob/main/charts/meilisearch/README.md
meilisearch:
  enabled: true
  environment:
    MEILI_ENV: 'production'
  resources:
    requests:
      memory: 40Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 6m
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: ebs.chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - ghcr.io

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  php:
    requests:
      memory: 100Mi
  caddy:
    requests:
      memory: 20Mi
  consumer:
    requests:
      memory: 100Mi
  fixtures:
    requests:
      memory: 100Mi

# If you use Mercure, you need the managed or the On Premise version to deploy more than one pod: https://mercure.rocks/docs/hub/cluster
replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
